#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.7
# In conjunction with Tcl version 8.6
#    Apr 18, 2016 05:58:16 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import test1_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel_1 (root)
    test1_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel_1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel_1 (w)
    test1_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel_1():
    global w
    w.destroy()
    w = None


class New_Toplevel_1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {DejaVu Sans} -size 20 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        font11 = "-family {DejaVu Sans} -size 24 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"

        top.geometry("1236x754+66+130")
        top.title("New Toplevel 1")
        top.configure(highlightcolor="black")



        self.Button1 = Button(top)
        self.Button1.place(relx=0.0, rely=0.56, height=337, width=627)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(font=font11)
        self.Button1.configure(state=ACTIVE)
        self.Button1.configure(text='''YES''')

        self.Button2 = Button(top)
        self.Button2.place(relx=0.51, rely=0.56, height=337, width=607)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(font=font11)
        self.Button2.configure(text='''NO''')

        self.Message1 = Message(top)
        self.Message1.place(relx=0.27, rely=0.2, relheight=0.27, relwidth=0.48)
        self.Message1.configure(font=font10)
        self.Message1.configure(text='''This program will collect your biometric information, including a photo of your face as well as your voice. Using this device conveys your acceptance of these terms. Tap YES to continue.''')
        self.Message1.configure(width=595)






if __name__ == '__main__':
    vp_start_gui()



